### ISSUE TITLE
Single Bash File

### ISSUE THREAD

**Issue by Isaacdelly** [PreciseMotion/precisepass#1]
Why are there multiple bash files for every operating system? It would make it much simpler to have a singular bash file that is partitioned by if statements. Something like this: [OS Detection in Bash](https://stackoverflow.com/questions/394230/how-to-detect-the-os-from-a-bash-script).

**Comment by AndrewKassab** [comment]
I don't think this strategy will work since both WSL and native linux have the values "linux-gnu" for $OSTYPE
